### ISSUE TITLE
Injecting SignInManager through DI causing issues when trying to resolve

### ISSUE THREAD

**Issue by pippinmole** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#47]
Using version 3.1.1:

ConfigureServices():
```cs
services.ConfigureMongoDbIdentity<ApplicationUser, ApplicationRole, Guid>(new MongoDbIdentityConfiguration {
    MongoDbSettings = new MongoDbSettings {
        ConnectionString = this._configuration.GetConnectionString("DatabaseConnectionString"),
        DatabaseName = "DatabaseName"
    },
    IdentityOptionsAction = options => {
        // ApplicationUser settings
        options.User.RequireUniqueEmail = true;
    }
});

services.AddScoped<IAppUserManager, AppUserManager>();
```

And trying to inject SignInManager<ApplicationUser> like so:

```cs
public AppUserManager(IConfiguration configuration, ILogger<AppUserManager> logger,
    UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager,
    IMapper mapper) {
    this._configuration = configuration;
    this._logger = logger;
    this._userManager = userManager;
    this._signInManager = signInManager;
    this._mapper = mapper;
}
```

Causes this error:

```
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: TokenTracker.TokenTracker.Core.User.IAppUserManager Lifetime: Scoped ImplementationType: TokenTracker.Token
Tracker.Core.User.AppUserManager': Unable to resolve service for type 'Microsoft.AspNetCore.Identity.SignInManager`1[TokenTracker.TokenTracker.Core.User.ApplicationUser]' while attempting to activate 'TokenTracker.TokenTracker.Core.User.AppUserManager'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: TokenTracker.TokenTracker.Core.User.IAppUserManager Lifetime: Scoped ImplementationType: TokenTracker.TokenTracker.Core.User.AppUserManager': Unable to resolve s
ervice for type 'Microsoft.AspNetCore.Identity.SignInManager`1[TokenTracker.TokenTracker.Core.User.ApplicationUser]' while attempting to activate 'TokenTracker.TokenTracker.Core.User.AppUserManager'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.SignInManager`1[TokenTracker.TokenTracker.Core.User.ApplicationUser]' while attempting to activate 'TokenTracker.TokenTracker.Core.User.AppUserManager'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at GetChain.Program.Main(String[] args) in C:\Users\icond\Documents\Coding\.NET Projects\GetChain\GetChain\Program.cs:line 7
```

I can however use version 2.1.1 with no issues.

**Comment by estradege** [comment]
Hello, I have the same problem when I update from 2.1.1 to 3.1.1. Have you find a fix for this?

**Comment by alexandre-spieser** [comment]
Hi, thanks for reaching out, have you compared your project with the sample project?

Here's the link to the startup class:
https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/blob/master/sample/MongoIdentitySample.Mvc/Startup.cs

There were breaking changes in 3.1.0: https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/releases/tag/3.1.0

**Comment by estradege** [comment]
Hi, thanks for your reply.
I'm using ConfigureMongoDbIdentity :
```csharp
services.ConfigureMongoDbIdentity<User, Role, ObjectId>(new MongoDbIdentityConfiguration
{
  MongoDbSettings = new MongoDbSettings
  {
      ...
  },
  IdentityOptionsAction = options =>
  {
      ...
  }
})
.AddSignInManager()
.AddDefaultTokenProviders();
```

Adding `AddSignInManager()` and `AddDefaultTokenProviders()` resolve the DI error but, raise a new one during the login process :
`
No sign-in authentication handlers are registered. Did you forget to call AddAuthentication().AddCookie("Identity.Application",...)?
`

Thank's for your help

**Comment by alexandre-spieser** [comment]
hmm that seems to be related to the auth middleware missing, are you calling AddAuthentication() ?
```
            services.AddIdentityCore<ApplicationUser>()
                    .AddRoles<MongoIdentityRole>()
                    .AddMongoDbStores<ApplicationUser, MongoIdentityRole, Guid>(settings.ConnectionString, settings.DatabaseName)
                    .AddSignInManager()
                    .AddDefaultTokenProviders();
```

 will not handle authentiction for you, referring to the sample startup class I linked, on line 44 you'll find
 
 ```
             services.AddAuthentication(o =>
            {
                o.DefaultScheme = IdentityConstants.ApplicationScheme;
                o.DefaultSignInScheme = IdentityConstants.ExternalScheme;
            })
            .AddIdentityCookies(o => { });
 ```

and later on 


```
            services.ConfigureApplicationCookie(options =>
            {
                // Cookie settings
                options.Cookie.HttpOnly = true;
                options.ExpireTimeSpan = TimeSpan.FromMinutes(5);

                options.LoginPath = "/Account/Login";
                options.SlidingExpiration = true;
            });
```

Please compare https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/blob/master/sample/MongoIdentitySample.Mvc/Startup.cs with your setup.
